name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_SERVER_IP }}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "Hello from GitHub Actions!"
            # Aquí puedes añadir los comandos que deseas ejecutar en tu servidor de Vultr
            # Ejemplo:
            # ssh user@server 'ls -la'
